spring:
  config:
    activate:
      on-profile:
        - oauth
        - mail
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: "${HELPER42_DB_USERNAME_RELEASE}"
    password: "${HELPER42_DB_PASSWORD_RELEASE}"
    url: "jdbc:mariadb://localhost:3306/${HELPER42_DB_NAME_RELEASE}"
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100
#Server
server:
  port: 8080
  error:
    whitelabel:
      enabled: false
#Log
logging:
  file:
    name: helper.log
#Sentry
Sentry:
  dsn: "${HELPER42_SENTRY_DSN}"
  environment: production
  logging:
    minimum-breadcrumb-level: error